(function_declaration name: (identifier) @name.function)
(method_declaration name: (field_identifier) @name.method)
(type_spec name: (type_identifier) @name.type)
(type_declaration (type_spec name: (type_identifier) @name.type))
(const_declaration (const_spec name: (identifier) @name.constant))
(var_declaration (var_spec name: (identifier) @name.variable))
