(function_item name: (identifier) @name.function)
(struct_item name: (type_identifier) @name.struct)
(enum_item name: (type_identifier) @name.enum)
(trait_item name: (type_identifier) @name.trait)
(mod_item name: (identifier) @name.module)
