#!/usr/bin/env bash
# One-time / refresh script: bundle Monaco Editor (ESM) into internal/server/web/monaco.
# Normal `go build` does not run this; commit the outputs.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/internal/server/web/monaco"
MONACO_VERSION="${MONACO_VERSION:-0.52.2}"

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

echo "Vendoring monaco-editor@${MONACO_VERSION} into ${OUT}"
cd "$TMP"
npm init -y >/dev/null
npm install "monaco-editor@${MONACO_VERSION}" esbuild --no-fund --no-audit

mkdir -p "$OUT"

# Entry that re-exports the full editor API (languages included via editor.main).
cat > entry.mjs <<'EOF'
import * as monaco from 'monaco-editor';
export default monaco;
export { monaco };
EOF

# Bundle main editor as ESM.
npx esbuild entry.mjs \
  --bundle \
  --format=esm \
  --outfile="$OUT/editor.bundle.js" \
  --loader:.ttf=file \
  --loader:.css=css \
  --asset-names=[name] \
  --public-path=/monaco/ \
  --minify

# Bundle workers as separate ESM modules (loaded via MonacoEnvironment.getWorker).
npx esbuild node_modules/monaco-editor/esm/vs/editor/editor.worker.js \
  --bundle --format=esm --minify --outfile="$OUT/editor.worker.js"
npx esbuild node_modules/monaco-editor/esm/vs/language/json/json.worker.js \
  --bundle --format=esm --minify --outfile="$OUT/json.worker.js"
npx esbuild node_modules/monaco-editor/esm/vs/language/css/css.worker.js \
  --bundle --format=esm --minify --outfile="$OUT/css.worker.js"
npx esbuild node_modules/monaco-editor/esm/vs/language/html/html.worker.js \
  --bundle --format=esm --minify --outfile="$OUT/html.worker.js"
npx esbuild node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js \
  --bundle --format=esm --minify --outfile="$OUT/ts.worker.js"

# Prefer esbuild-emitted CSS (rewritten font URLs under /monaco/).
if [[ -f "$OUT/editor.bundle.css" ]]; then
  mv -f "$OUT/editor.bundle.css" "$OUT/editor.main.css"
elif [[ -f "$OUT/entry.css" ]]; then
  mv -f "$OUT/entry.css" "$OUT/editor.main.css"
fi
# Codicon font: copy from package if not already emitted by esbuild.
if [[ ! -f "$OUT/codicon.ttf" ]]; then
  find node_modules/monaco-editor -name 'codicon.ttf' -print -quit | while read -r f; do
    cp "$f" "$OUT/codicon.ttf"
  done
fi

printf '%s\n' "$MONACO_VERSION" > "$OUT/VERSION"

cat > "$OUT/README.md" <<EOF
# Vendored Monaco Editor (ESM)

Version: ${MONACO_VERSION}

Generated by \`scripts/vendor-monaco.sh\`. Do not use the deprecated AMD \`/min\` build.

Refresh:

\`\`\`bash
./scripts/vendor-monaco.sh
# optional: MONACO_VERSION=0.52.2 ./scripts/vendor-monaco.sh
\`\`\`

Commit the outputs under this directory. \`go build\` embeds them; npm is not required at build time.
EOF

echo "Done. Outputs:"
ls -lah "$OUT"
