#!/usr/bin/env bash
# One-time / refresh script: vendor @xterm/xterm (UMD) into internal/server/web/xterm.
# Normal `go build` does not run this; commit the outputs.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/internal/server/web/xterm"
XTERM_VERSION="${XTERM_VERSION:-latest}"
FIT_VERSION="${FIT_VERSION:-latest}"

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

cd "$TMP"
npm init -y >/dev/null
npm install "@xterm/xterm@${XTERM_VERSION}" "@xterm/addon-fit@${FIT_VERSION}" --no-fund --no-audit

# Resolve the actually-installed versions (defaults install "latest").
XTERM_RESOLVED="$(node -p "require('./node_modules/@xterm/xterm/package.json').version")"
FIT_RESOLVED="$(node -p "require('./node_modules/@xterm/addon-fit/package.json').version")"

echo "Vendoring @xterm/xterm@${XTERM_RESOLVED} + @xterm/addon-fit@${FIT_RESOLVED} into ${OUT}"

mkdir -p "$OUT"

# Prebuilt UMD bundles — copy from the packages as-is (no bundling step).
cp node_modules/@xterm/xterm/lib/xterm.js "$OUT/xterm.js"
cp node_modules/@xterm/addon-fit/lib/addon-fit.js "$OUT/addon-fit.js"
cp node_modules/@xterm/xterm/css/xterm.css "$OUT/xterm.css"

{
  echo "xterm=${XTERM_RESOLVED}"
  echo "addon-fit=${FIT_RESOLVED}"
} > "$OUT/VERSION"

cat > "$OUT/README.md" <<EOF
# Vendored xterm.js (UMD)

- @xterm/xterm@${XTERM_RESOLVED}
- @xterm/addon-fit@${FIT_RESOLVED}

Generated by \`scripts/vendor-xterm.sh\`. Refresh:

\`\`\`bash
./scripts/vendor-xterm.sh
# installs the latest published versions; pin for reproducible refreshes:
# XTERM_VERSION=6.0.0 FIT_VERSION=0.11.0 ./scripts/vendor-xterm.sh
\`\`\`

Commit the outputs under this directory. \`go build\` embeds them; npm is not required at build time.
EOF

# Copy licenses for attribution.
cp node_modules/@xterm/xterm/LICENSE "$OUT/xterm.LICENSE" 2>/dev/null || true
cp node_modules/@xterm/addon-fit/LICENSE "$OUT/addon-fit.LICENSE" 2>/dev/null || true

echo "Done. Outputs:"
ls -lah "$OUT"
