#!/usr/bin/env bash
# One-time / refresh script: vendor marked + DOMPurify into internal/server/web/vendor.
# Normal `go build` does not run this; commit the outputs.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/internal/server/web/vendor"
MARKED_VERSION="${MARKED_VERSION:-18.0.6}"
DOMPURIFY_VERSION="${DOMPURIFY_VERSION:-3.2.6}"

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

echo "Vendoring marked@${MARKED_VERSION} + dompurify@${DOMPURIFY_VERSION} into ${OUT}"
cd "$TMP"
npm init -y >/dev/null
npm install "marked@${MARKED_VERSION}" "dompurify@${DOMPURIFY_VERSION}" esbuild --no-fund --no-audit

mkdir -p "$OUT"

# Bundle marked as a single ESM module.
cat > marked-entry.mjs <<'EOF'
export { marked } from 'marked';
EOF

npx esbuild marked-entry.mjs \
  --bundle \
  --format=esm \
  --minify \
  --outfile="$OUT/marked.esm.js"

# Bundle DOMPurify as ESM (browser-only; no jsdom).
cat > purify-entry.mjs <<'EOF'
import DOMPurify from 'dompurify';
export default DOMPurify;
export { DOMPurify };
EOF

npx esbuild purify-entry.mjs \
  --bundle \
  --format=esm \
  --minify \
  --outfile="$OUT/dompurify.esm.js" \
  --platform=browser

{
  echo "marked=${MARKED_VERSION}"
  echo "dompurify=${DOMPURIFY_VERSION}"
} > "$OUT/VERSION"

cat > "$OUT/README.md" <<EOF
# Vendored Markdown (ESM)

- marked@${MARKED_VERSION}
- dompurify@${DOMPURIFY_VERSION}

Generated by \`scripts/vendor-markdown.sh\`. Refresh:

\`\`\`bash
./scripts/vendor-markdown.sh
\`\`\`

Commit the outputs under this directory. \`go build\` embeds them; npm is not required at build time.
EOF

# Copy licenses for attribution.
cp node_modules/marked/LICENSE.md "$OUT/marked.LICENSE.md" 2>/dev/null \
  || cp node_modules/marked/LICENSE "$OUT/marked.LICENSE.md"
cp node_modules/dompurify/LICENSE "$OUT/dompurify.LICENSE" 2>/dev/null || true

echo "Done. Outputs:"
ls -lah "$OUT"
