package llm

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
)

// TestUUIDV5CrossImplementation pins the uuidV5 core against values
// generated by CPython's uuid.uuid5 (the reference implementation of the
// RFC 4122 §4.3 algorithm) for two different namespaces. A silent bit
// mistake in the version/variant forcing would be invisible in the
// integration tests below.
func TestUUIDV5CrossImplementation(t *testing.T) {
	cases := []struct {
		name      string
		namespace [16]byte
		input     string
		want      string
	}{
		{
			name:      "DNS namespace, example.org",
			namespace: [16]byte{0x6b, 0xa7, 0xb8, 0x11, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8},
			input:     "example.org",
			want:      "54a35416-963c-5dd6-a1e2-5ab7bb5bafc7",
		},
		{
			name:      "URL namespace, www.ietf.org",
			namespace: [16]byte{0x6b, 0xa7, 0xb8, 0x12, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8},
			input:     "www.ietf.org",
			want:      "cc6eb518-0a59-571a-a4c3-e310cf1ae46b",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := uuidV5(tc.namespace, tc.input); got != tc.want {
				t.Fatalf("uuidV5 = %q, want %q (CPython uuid.uuid5)", got, tc.want)
			}
		})
	}
}

// TestSessionUUIDDeterministic pins the derivation contract: same session ID
// → same UUID (stable across restarts of a resumed session), different IDs
// differ, empty/whitespace → no header value.
func TestSessionUUIDDeterministic(t *testing.T) {
	a := SessionUUID("abc123")
	if a == "" {
		t.Fatal("SessionUUID returned empty for a non-empty id")
	}
	if got := SessionUUID("abc123"); got != a {
		t.Errorf("second derivation = %q, want %q (must be deterministic)", got, a)
	}
	if got := SessionUUID("  abc123  "); got != a {
		t.Errorf("trimmed derivation = %q, want %q (whitespace must be trimmed)", got, a)
	}
	if b := SessionUUID("abc124"); b == a {
		t.Error("different session IDs derived the same UUID")
	}
	// Canonical dashed form: 8-4-4-4-12, version nibble 5, variant 10xx.
	parts := strings.Split(a, "-")
	if len(parts) != 5 || len(parts[0]) != 8 || len(parts[1]) != 4 || len(parts[2]) != 4 || len(parts[3]) != 4 || len(parts[4]) != 12 {
		t.Errorf("UUID %q is not in canonical 8-4-4-4-12 form", a)
	}
	if a[14] != '5' {
		t.Errorf("UUID %q version nibble = %q, want 5", a, a[14:15])
	}
	if !strings.ContainsRune("89ab", rune(a[19])) {
		t.Errorf("UUID %q variant nibble = %q, want 8/9/a/b", a, a[19:20])
	}
	if SessionUUID("") != "" || SessionUUID("   ") != "" {
		t.Error("empty/whitespace session ID must derive no header value")
	}
}

// TestSessionHeaderStateConcurrent hammers SetSessionID and uuid() from
// goroutines; the race detector validates the atomic publish. A read may
// observe any concurrently published id, so only membership in the valid
// derived set is asserted.
func TestSessionHeaderStateConcurrent(t *testing.T) {
	st := newSessionHeaderState()
	valid := map[string]bool{
		"":                 true,
		SessionUUID("s"):   true,
		SessionUUID("ss"):  true,
		SessionUUID("sss"): true,
	}
	var wg sync.WaitGroup
	for i := 0; i < 8; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			for j := 0; j < 200; j++ {
				st.SetSessionID(strings.Repeat("s", i%3+1))
				if got := st.uuid(); !valid[got] {
					t.Errorf("uuid() = %q, not a valid derived value", got)
					return
				}
			}
		}(i)
	}
	wg.Wait()
	st.SetSessionID("")
	if got := st.uuid(); got != "" {
		t.Errorf("uuid() after clear = %q, want empty", got)
	}
}

// headerCaptureServer records the X-Opencode-Session header (and User-Agent
// as a control) per request path.
func headerCaptureServer(t *testing.T) (*httptest.Server, *map[string]string) {
	t.Helper()
	var mu sync.Mutex
	headers := make(map[string]string)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		headers[r.URL.Path] = r.Header.Get(SessionHeaderName)
		mu.Unlock()
		switch r.URL.Path {
		case "/v1/models":
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(map[string]any{
				"object": "list",
				"data":   []map[string]any{},
			})
		default:
			w.WriteHeader(http.StatusNoContent)
		}
	}))
	t.Cleanup(srv.Close)
	return srv, &headers
}

// TestNewClientPairSessionHeader verifies the transport wrapping: with a
// session set, every request carries the derived UUID; clearing the session
// drops the header; switching sessions switches the value.
func TestNewClientPairSessionHeader(t *testing.T) {
	srv, headers := headerCaptureServer(t)
	st := newSessionHeaderState()
	stream, _ := newClientPair(srv.URL+"/v1", "test-key", st)

	// No session yet → no header.
	if _, err := stream.Models.List(context.Background()); err != nil {
		t.Fatalf("Models.List: %v", err)
	}
	if got := (*headers)["/v1/models"]; got != "" {
		t.Fatalf("header before SetSessionID = %q, want empty", got)
	}

	st.SetSessionID("sess-1")
	if _, err := stream.Models.List(context.Background()); err != nil {
		t.Fatalf("Models.List: %v", err)
	}
	if got := (*headers)["/v1/models"]; got != SessionUUID("sess-1") {
		t.Fatalf("header = %q, want %q", got, SessionUUID("sess-1"))
	}

	st.SetSessionID("sess-2")
	if _, err := stream.Models.List(context.Background()); err != nil {
		t.Fatalf("Models.List: %v", err)
	}
	if got := (*headers)["/v1/models"]; got != SessionUUID("sess-2") {
		t.Fatalf("header after switch = %q, want %q", got, SessionUUID("sess-2"))
	}

	st.SetSessionID("")
	if _, err := stream.Models.List(context.Background()); err != nil {
		t.Fatalf("Models.List: %v", err)
	}
	if got := (*headers)["/v1/models"]; got != "" {
		t.Fatalf("header after clear = %q, want empty", got)
	}
}

// TestNewClientPairNoStateUntagged pins that a nil state (direct-constructed
// providers) leaves the clients untagged.
func TestNewClientPairNoStateUntagged(t *testing.T) {
	srv, headers := headerCaptureServer(t)
	stream, _ := newClientPair(srv.URL+"/v1", "test-key", nil)
	if _, err := stream.Models.List(context.Background()); err != nil {
		t.Fatalf("Models.List: %v", err)
	}
	if got := (*headers)["/v1/models"]; got != "" {
		t.Fatalf("header with nil state = %q, want empty", got)
	}
}

// TestBuildProfileClientsSessionHeaderGating pins the endpoint gating: a
// non-OpenCode profile's clients never carry the header (no internal header
// leakage to third-party endpoints), while the header value the OpenCode
// clients would send is the derived UUID (the wrapping itself is covered by
// TestNewClientPairSessionHeader; the zen/go twins hardcode the production
// OpenCode URLs, so they are exercised structurally here).
func TestBuildProfileClientsSessionHeaderGating(t *testing.T) {
	srv, headers := headerCaptureServer(t)
	st := newSessionHeaderState()
	st.SetSessionID("sess-gate")

	// Non-OpenCode profile: stream + catalog clients stay untagged.
	plain := buildProfileClients(providerProfile{
		name:    "default",
		baseURL: srv.URL + "/v1",
		apiKey:  "test-key",
	}, st)
	if plain.zenStream != nil || plain.goStream != nil {
		t.Fatal("non-OpenCode profile must not build zen/go twins")
	}
	if _, err := plain.stream.Models.List(context.Background()); err != nil {
		t.Fatalf("Models.List: %v", err)
	}
	if got := (*headers)["/v1/models"]; got != "" {
		t.Fatalf("non-OpenCode stream client sent header %q, want none", got)
	}

	// OpenCode profile: twins exist and the shared state carries the
	// derived UUID they will inject.
	oc := buildProfileClients(providerProfile{
		name:    "opencode",
		baseURL: "https://opencode.ai/zen/v1/",
		apiKey:  "test-key",
	}, st)
	if oc.zenStream == nil || oc.zenCatalog == nil || oc.goStream == nil || oc.goCatalog == nil {
		t.Fatal("OpenCode profile must build all four zen/go clients")
	}
	if oc.catalog != nil {
		t.Fatal("OpenCode profile's plain catalog client must stay nil")
	}
	if got := st.uuid(); got != SessionUUID("sess-gate") {
		t.Fatalf("state uuid = %q, want %q", got, SessionUUID("sess-gate"))
	}
}

// TestSetProfilesKeepsSessionHeader pins that SetProfiles rebuilds the
// clients against the SAME session-header state: a session set before the
// profile swap survives the rebuild (the new OpenCode clients would tag
// requests with it), and rebuilt non-OpenCode clients stay untagged.
func TestSetProfilesKeepsSessionHeader(t *testing.T) {
	srv, headers := headerCaptureServer(t)
	p := NewOpenAIProviderWithProfiles(
		[]ProviderProfile{{Name: "default", BaseURL: srv.URL + "/v1", APIKey: "k", Model: "m"}},
		"m", t.TempDir(), nil)
	p.SetSessionID("sess-swap")

	if err := p.SetProfiles([]ProviderProfile{{Name: "second", BaseURL: srv.URL + "/v1", APIKey: "k", Model: "m"}}); err != nil {
		t.Fatalf("SetProfiles: %v", err)
	}
	if p.sessionHdr == nil {
		t.Fatal("SetProfiles must keep the session-header state")
	}
	if got := p.sessionHdr.uuid(); got != SessionUUID("sess-swap") {
		t.Fatalf("uuid after SetProfiles = %q, want %q", got, SessionUUID("sess-swap"))
	}
	if _, err := p.ListModels(context.Background()); err != nil {
		t.Fatalf("ListModels after SetProfiles: %v", err)
	}
	if got := (*headers)["/v1/models"]; got != "" {
		t.Fatalf("rebuilt non-OpenCode client sent header %q, want none", got)
	}
}
